### ISSUE TITLE
Cas d'utilisation : Gérer les clients (version abrégée)

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#10]
Cas d'utilisation 6
Nom : gérer les clients

- Identifier les acteurs
- Faire un résumé
- Déterminer les preconditions et postconditions
- Déterminer les scénarios alternatifs
- Créer diagramme

https://docs.google.com/document/d/18ESnYfYp2TsGHYZq1l03XsSu7DpvfLjiUWsDVzWXej8/edit?usp=sharing

**Comment by michelicious11** [comment]
@20100gervais 
juste la version abrégée au final (ce sera de même avec toutes les opérations admin)

**Comment by 20100gervais** [comment]
@michelicious11 @Staluk33 reviewer ca svp

**Comment by Staluk33** [comment]
@20100gervais ça l'air all good selon moi
