### ISSUE TITLE
Cas d'utilisation : Créer des rapports (version abrégée)

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#11]
Cas d'utilisation 7
Nom : créer des rapports

- Identifier les acteurs
- Faire un résumé
- Déterminer les preconditions et postconditions
- Déterminer les scénarios alternatifs
- Créer diagramme

https://docs.google.com/document/d/18ESnYfYp2TsGHYZq1l03XsSu7DpvfLjiUWsDVzWXej8/edit?usp=sharing

**Comment by michelicious11** [comment]
@20100gervais 
Juste la version abrégée

**Comment by 20100gervais** [comment]
@FilipNajj @Staluk33 reviewer ca svp, c'est tres petit comme cas mais jai peut etre manquer dequoi 
quelques esquisses de l'interface en progress ici 
https://github.com/michelicious11/Locar-Xpress/issues/28

**Comment by Staluk33** [comment]
@20100gervais  Est-ce que tu peux avoir l'option d'imprimer un rapport ou il fait juste s'afficher ? Dans le cas ou c'est juste afficher le cas abrégé est all good.
