### ISSUE TITLE
Cas d'utilisation : Traiter un paiement (version détaillée)

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#20]
Cas d'utilisation 9
Nom : traiter un paiement

- Identifier les acteurs
- Faire un résumé
- Déterminer les preconditions et postconditions
- Déterminer les scénarios alternatifs
- Créer diagramme

https://docs.google.com/document/d/18ESnYfYp2TsGHYZq1l03XsSu7DpvfLjiUWsDVzWXej8/edit?usp=sharing

**Comment by michelicious11** [comment]
@FilipNajj 
Faire une version détaillée

**Comment by michelicious11** [comment]
@Staluk33 a deja fait le diagramme

@FilipNajj @GreekProgrammingGod pour le review

**Comment by FilipNajj** [comment]
@Staluk33  Je ne vois pas le cas d'utilisation dans le document

**Comment by Staluk33** [comment]
[](url
[Traiter paiement.docx](https://github.com/michelicious11/Locar-Xpress/files/7529929/Traiter.paiement.docx)
)
Traiter un paiement
Tiens Filip voici le document @FilipNajj
