### ISSUE TITLE
Cas d'utilisation : Imprimer (créer?) le contrat de location (version abrégée)

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#21]
Cas d'utilisation 9
Nom : imprimer le contrat de location

- Identifier les acteurs
- Faire un résumé
- Déterminer les preconditions et postconditions
- Déterminer les scénarios alternatifs
- Créer diagramme

https://docs.google.com/document/d/18ESnYfYp2TsGHYZq1l03XsSu7DpvfLjiUWsDVzWXej8/edit?usp=sharing

**Comment by michelicious11** [comment]
@FilipNajj 
juste faire une version abrégée

**Comment by FilipNajj** [comment]
@michelicious11 
@GreekProgrammingGod 
Review

Je pense ca sera mieux "Creer un contrat" a la place de "Imprimer un contrat"

**Comment by FilipNajj** [comment]
@michelicious11  
Je pense ca sera mieux "Creer un contrat" a la place de "Imprimer un contrat"
