### ISSUE TITLE
Cas d'utilisation : Gerer les employes (version abrégée)

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#22]
Cas d'utilisation 11
Nom : gerer les employes

- Identifier les acteurs
- Faire un résumé
- Déterminer les preconditions et postconditions
- Déterminer les scénarios alternatifs
- Créer diagramme

https://docs.google.com/document/d/18ESnYfYp2TsGHYZq1l03XsSu7DpvfLjiUWsDVzWXej8/edit?usp=sharing

**Comment by michelicious11** [comment]
@20100gervais 
Juste faire une version abrégée au final

**Comment by 20100gervais** [comment]
@michelicious11 @GreekProgrammingGod  reviewer ca i guess
