### ISSUE TITLE
Cas d'utilisation : Soumettre une reclamation aux assurances (version abrégée)

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#23]
Cas d'utilisation 12
Nom : faire une reclamation

- Identifier les acteurs
- Faire un résumé
- Déterminer les preconditions et postconditions
- Déterminer les scénarios alternatifs
- Créer diagramme

https://docs.google.com/document/d/18ESnYfYp2TsGHYZq1l03XsSu7DpvfLjiUWsDVzWXej8/edit?usp=sharing

**Comment by michelicious11** [comment]
@FilipNajj 
@20100gervais 

A review.

**Comment by michelicious11** [comment]
@Staluk33 
A recommencer, version abregee seulement (je vais le remettre dans in-progress)

**Comment by Staluk33** [comment]
je comprend pas la soumission d'une réclamation. C'est pas le client qui est supossé le faire par lui-même ?
