### ISSUE TITLE
Cas d'utilisation : Inspecter un vehicule (version abrégée)

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#24]
Cas d'utilisation 13
Nom : inspecter un vehicule

- Identifier les acteurs
- Faire un résumé
- Déterminer les preconditions et postconditions
- Déterminer les scénarios alternatifs
- Créer diagramme

https://docs.google.com/document/d/18ESnYfYp2TsGHYZq1l03XsSu7DpvfLjiUWsDVzWXej8/edit?usp=sharing

**Comment by michelicious11** [comment]
@Staluk33 
Juste faire une version abrégée

**Comment by Staluk33** [comment]
[](url
[inspection vehicule.docx](https://github.com/michelicious11/Locar-Xpress/files/7529695/inspection.vehicule.docx)
)
Inspection du véhicule
@michelicious11 @20100gervais
