### ISSUE TITLE
Creer l'esquisse pour la page "Gestion" 

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#28]
Il faut avoir les elements qui permettent de rendre l'app scalable

soit pouvoir ajouter, modifier ou supprimer : 
- des clients
- des vehicules
- des utilisateurs (du logiciel)

On devrait pouvoir creer des rapports et modificier le contrat de location (les prix et tarifs)

**Comment by 20100gervais** [comment]
@michelicious11 
j'avais l'impression qu'on pouvait ajouter et enlever une voiture a partir de l'onglet voiture (même chose pour clients dans l'onglet client)
on devrais exclure ces fonctions de l'onglet Gestion pour éviter la redondance?

**Comment by michelicious11** [comment]
@20100gervais 
En fait non, parce que tu ne veux pas que l'utilisateur ait ce pouvoir la. 
L'onglet voiture est plutot la a des fins de consultation (catalogue de voiture que tu peux montrer au client) 
par contre tas raison, jsuis plus sur que gestion **client** soit relevant mnt

**Comment by 20100gervais** [comment]
@michelicious11 
je pensais que c'était l'employé qui fesait la reservation pour le client. 
l'utilisateur ne toucherais pas a l'interface.
on avait juste parler de ca rapidement dans la rencontre so je suis pas sur.
dans ce cas on aurait pas besoin de repeter cette fonction car les employés et les admins ont acces à ces onglets.
dans l'onglet voiture, on dirait qu'on peut ajouter des voitures (dans le rectangle avec le + vert) so c'est pas juste pour consulter

**Comment by michelicious11** [comment]
@20100gervais 
yep t'as raison, jai juste fait ca vite mais on ne devrait pas pouvoir ajouter des voitures en tant qu'utilisateur...

Il y a quand meme un catalogue que le client peut consulter et le prepose doit pouvoir voir si un vehicule est dispo ou non, mais il ne devrait pas pouvoir ajouter/modifier/supprimer des voitures... 

peut-etre on aurait meme pas besoin d'un onglet gestion mais juste d'un onglet utilisateurs qui apparait plutot et des vues differentes sur les pages voitures et clients (avec des fonctions additionnelles pour les admin)

**Comment by michelicious11** [comment]
Je vais quand meme garder les croquis pour montrer l'evolution de la conception de l'app et elaborer sur cette modification quon va devoir faire. Nice catch Vince :)

**Comment by 20100gervais** [comment]
![Interface_Voitures-Vue_admin](https://user-images.githubusercontent.com/46601313/141535333-5a5d6402-7f29-402f-af80-6c73d3223dac.png)
So l`onglet voiture aurait pt l`air de ca pour les admins?
presque meme chose pour l'onglet client et utilisateurs

**Comment by 20100gervais** [comment]
![Interface_Parametre_Admin-5](https://user-images.githubusercontent.com/46601313/141536282-8a878a84-f698-40d8-81fb-edf04b37ca2e.png)
ici, seulement l`admin pourrait voir les options "contrat de location" et 'rapports'
