### ISSUE TITLE
Creer l'esquisse et la page "formulaire depart"

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#32]
Lorsqu'un client vient louer une auto, il doit choisir plusieurs options. Le formulaire sera pour recueillir cette information. 
Il devrait y avoir : 

- des inputs pour les informations du client + consulter la base de donnees des clients deja existents
- dates (depart et retour) (objets calendrier)
- vehicule
- assurances ou non (boutons radios)
- validation des aptitudes (permis et date de naissance (calendrier)) 
- etc. 

Ca doit rester intuitif et coherent avec le reste de l'app... bonne chance!

**Comment by michelicious11** [comment]
La page formulaire de reservation et de retour devraient se ressembler donc le faire ensemble idealement

**Comment by FilipNajj** [comment]
![Screenshot from 2021-11-27 00-44-29](https://user-images.githubusercontent.com/77418685/143669683-5f9bbc6f-57ec-462f-87a5-ff49604d7cf9.png)
@michelicious11 
@GreekProgrammingGod 
Review

**Comment by GreekProgrammingGod** [comment]
very nice
