### ISSUE TITLE
Payer amende (version abregee)

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#42]
Juste faire la description abregee

**Comment by michelicious11** [comment]
@GreekProgrammingGod 
faut tu tag 2 personnes ou plus pour qu'ils review.
Je vais le faire avec @20100gervais

**Comment by GreekProgrammingGod** [comment]
5. Le système compare la date et l’heure de retour et la date de l’heure dans le contrat de location et traite la facture en conséquence
    5a. La différence entre la date et l’heure de retour est de moins de 30 minutes de la date et l’heure indiqué dans le contrat :
        1. Aucun frais de retard est ajouté à la facture.
    5b. La différence entre la date et l’heure de retour est de plus de 30 minutes de la date et l’heure indiqué dans le contrat 
        1. Un supplément de 10 % du prix de la location quotidienne, par heure de retard jusqu’à concurrence du tarif quotidien 
            est imposé
@michelicious11 @20100gervais
