### ISSUE TITLE
Cas d'utilisation : Retourner un véhicule (version détaillée)

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#6]
Cas d'utilisation 2
Nom : retourner un vehicule

- Identifier les acteurs
- Faire un résumé
- Déterminer les preconditions et postconditions
- Déterminer les scénarios alternatifs
- Créer diagramme

https://docs.google.com/document/d/18ESnYfYp2TsGHYZq1l03XsSu7DpvfLjiUWsDVzWXej8/edit?usp=sharing

**Comment by GreekProgrammingGod** [comment]
![image](https://user-images.githubusercontent.com/59322239/141600691-bba4fe6f-c14f-4a3e-8d08-0a2691aa9156.png)
![image](https://user-images.githubusercontent.com/59322239/141600705-f93f6e0b-174e-4579-bd6e-2831506cad03.png)
@FilipNajj @Staluk33

**Comment by Staluk33** [comment]
@GreekProgrammingGod 

- regardes tes # d'étapes ils ne se suivent pas. 

- Dans ton étape 10 est-ce que tu voulais dire "Le système compare la date et l'heure de retour et **la date et l'heure dans le contrat** de location...." ?

- regarde ton "font" je pense qu'il n'est pas le même
