### ISSUE TITLE
Cas d'utilisation : Modifier (ou supprimer) une location 

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#7]
Cas d'utilisation 3
Nom : modifier une location

- Identifier les acteurs
- Faire un résumé
- Déterminer les preconditions et postconditions
- Déterminer les scénarios alternatifs
- Créer diagramme

https://docs.google.com/document/d/18ESnYfYp2TsGHYZq1l03XsSu7DpvfLjiUWsDVzWXej8/edit?usp=sharing

**Comment by Staluk33** [comment]
[](url
[Modifier ou supprimer une location.docx](https://github.com/michelicious11/Locar-Xpress/files/7529850/Modifier.ou.supprimer.une.location.docx)
)
Modifier ou supprimer une location 
@FilipNajj @GreekProgrammingGod
