### ISSUE TITLE
Cas d'utilisation : Consulter les locations (version abrégée)

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#8]
Cas d'utilisation 4
Nom : consulter les locations

- Identifier les acteurs
- Faire un résumé
- Déterminer les preconditions et postconditions
- Déterminer les scénarios alternatifs
- Créer diagramme

https://docs.google.com/document/d/18ESnYfYp2TsGHYZq1l03XsSu7DpvfLjiUWsDVzWXej8/edit?usp=sharing

**Comment by Staluk33** [comment]
@michelicious11 @FilipNajj

**Comment by michelicious11** [comment]
@Staluk33 
Juste faire une version abrégée. Je remet la tache a in-progress.

**Comment by Staluk33** [comment]
[](url
[Consulter les locations.docx](https://github.com/michelicious11/Locar-Xpress/files/7529675/Consulter.les.locations.docx)
)
Consulter les locations (à review)
@GreekProgrammingGod @FilipNajj
