### ISSUE TITLE
Cas d'utilisation : Gérer les véhicules (version abrégée)

### ISSUE THREAD

**Issue by michelicious11** [michelicious11/Locar-Xpress#9]
Cas d'utilisation 5
Nom : gérer les véhicules

- Identifier les acteurs
- Faire un résumé
- Déterminer les preconditions et postconditions
- Déterminer les scénarios alternatifs
- Créer diagramme

https://docs.google.com/document/d/18ESnYfYp2TsGHYZq1l03XsSu7DpvfLjiUWsDVzWXej8/edit?usp=sharing

**Comment by 20100gervais** [comment]
[Diagramme Gestion des véhicules.pdf](https://github.com/michelicious11/Locar-Xpress/files/7508992/Diagramme.Gestion.des.vehicules.pdf)

**Comment by michelicious11** [comment]
Ca devrait un peu plus ressembler a ca genre

le systeme c'est la "boite", log in cest un include pcq tu dois te log in pour tous les scenarios avant de commencer...jai ajoute des cas...jsais pas sil aurait autre chose mais tk cest a la main lol 


![IMG_3613](https://user-images.githubusercontent.com/46691861/141030042-6bc1181f-2e05-4473-8d39-094a56ea0c94.jpg)

**Comment by michelicious11** [comment]
@20100gervais 
oh yeah il aurait probablement un acteur systeme inventaire et un comptabilite (donc la t'utiliserais ton <<sys x>> pcq ce sont des acteurs non humain. Pis pour les ajout/modifier/supprimer, ce sont des extends.

**Comment by michelicious11** [comment]
@20100gervais 
juste créer une version abrégée au final

**Comment by 20100gervais** [comment]
@GreekProgrammingGod @FilipNajj reviewer ca svp
